#!/bin/sh

# Usage: test-gcc [MAKE_TARGET...]

set -e

script_dir=$(realpath $(dirname "$0"))

export CXX=g++
export CC=gcc

CI_SANITIZER=address    "$script_dir"/make-with-sanitizer $@
CI_SANITIZER=thread     "$script_dir"/make-with-sanitizer $@
CI_SANITIZER=undefined  "$script_dir"/make-with-sanitizer $@
