#!/bin/bash

# Usage: test-clang [MAKE_TARGET...]

set -e

script_dir=$(realpath $(dirname "$0"))

export CXX=${CXX:-clang++}
export CC=${CC:-clang}

CI_SANITIZER=memory    "$script_dir"/make-with-sanitizer $@
